name = "pheromone-parfums"
main = "agent/src/index.js"
compatibility_date = "2023-10-02"

[site]
bucket = "./blog/_site"

[ai]
binding = "AI"

[triggers]
crons = ["0 3 * * *"]

[vars]
GITHUB_REPO_NAME = "pheromoneparfums"
GITHUB_REPO_OWNER = "katalagahakim"
MAX_REVIEWS_PER_RUN = "1"
MAX_REVIEWS_TOTAL = "50"
